version: 2
updates:
  # Ecosistema
  - package-ecosystem: "gradle"
    # Directorio raiz del proyecto android
    directory: "/calculadoraVelocidadMedia"
    # Rama de destino para las actualizaciones
    target-branch: "desarrollo"
    # Intervalo de actualización
    schedule:
      interval: "daily"