name: CI/CD Pipeline

# Configuración de eventos que disparan el workflow
on:
  push:
    branches: [desarrollo, main]
    tags:
      - 'calculadoraVelocidadMedia-*'
  pull_request:
    branches: [desarrollo]
    paths-ignore: ['**.md']

    # Variables de entorno para la configuración del SDK y JDK
env:
  ANDROID_COMPILE_SDK: "36.1"
  ANDROID_BUILD_TOOLS: "36.0.0"
  ANDROID_SDK_TOOLS: "14742923"
  JAVA_VERSION: "21"

jobs:
  # 1. Análisis del lint basico
  lint:
    name: Android Lint
    runs-on: ubuntu-24.04
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Configura JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      # Configura Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      # Ejecuta el análisis de lint
      - name: Run Android Lint
        working-directory: calculadoraVelocidadMedia
        run: |
          chmod +x gradlew
          ./gradlew -Pci --console=plain :app:lint -PbuildDir=lint

      # Sube el reporte de lint como artefacto
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: calculadoraVelocidadMedia/app/lint/reports/lint-results-debug.html
          retention-days: 5

  # 2. Análisis de estilo de código con Ktlint
  ktlint-check:
    name: Ktlint Check
    runs-on: ubuntu-24.04
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Configura JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      # Configura Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      # Ejecuta el análisis de ktlint
      - name: Run ktlintCheck
        working-directory: calculadoraVelocidadMedia
        run: |
          chmod +x gradlew
          ./gradlew -Pci --console=plain ktlintCheck -PbuildDir=ktlint

      # Sube el reporte de ktlint como artefacto
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ktlint-report
          path: calculadoraVelocidadMedia/app/ktlint/reports/*.txt
          retention-days: 5

  # 3. Compilación aplicación
  assemble:
    name: Assemble Normal APK
    runs-on: ubuntu-24.04
    needs: [lint, ktlint-check]
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Configura JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      # Configura Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      # Compila el APK normal
      - name: Assemble Normal APK
        working-directory: calculadoraVelocidadMedia
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      # Sube el APK normal como artefacto
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: release-apk
          path: calculadoraVelocidadMedia/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 5

  # 4. Ejecución de pruebas unitarias
  testsUnitarias:
    name: Run Tests
    runs-on: ubuntu-24.04
    needs: [assemble]
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Configura JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      # Habilitar KVM en el ejecutor para aceleración por hardware nativa
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Corre el emulador y ejecuta el script
      - name: Run Android instrumented & unit tests
        working-directory: calculadoraVelocidadMedia
        run: |
          chmod +x gradlew
          ./gradlew app:test

  # 5. Ejecución de pruebas instrumentadas
  testsInstrumentados:
    name: Run Tests
    runs-on: ubuntu-24.04
    needs: [assemble]
    strategy:
      matrix:
        api-level: [24,25,26,27,28,29,30,31,32,33,34,35,36]
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Configura JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      # Habilitar KVM en el ejecutor para aceleración por hardware nativa
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Corre el emulador y ejecuta el script
      - name: Run Android instrumented & unit tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          profile: pixel_2
          working-directory: ./calculadoraVelocidadMedia
          script: |
            chmod +x gradlew
            ./gradlew app:connectedAndroidTest



  # 6. Ensamblado y firmado del APK de release
  assemble-release:
    name: Assemble & Sign Release APK
    runs-on: ubuntu-24.04
    needs: [testsUnitarias, testsInstrumentados]
    # Se ejecuta en master o ante la presencia de un tag
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Configura JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'gradle'

      # Configura Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      # Descarga el keystore codificado en base64 desde los secretos y lo decodifica
      - name: Download base64-encoded keystore from secrets
        env:
          CI_CD_KEYSTORE_BASE64: ${{ secrets.CI_CD_KEYSTORE_BASE64 }}
        run: |
          echo "$CI_CD_KEYSTORE_BASE64" | base64 -d > calculadoraVelocidadMedia/fichero.jks

      # Firma el apk de release con apksigner usando las credenciales almacenadas en los secretos
      - name: Assemble Release APK & Sign it with apksigner
        working-directory: calculadoraVelocidadMedia
        env:
          CI_KEYSTORE_PASSWORD: ${{ secrets.CI_KEYSTORE_PASSWORD }}
          CI_KEY_ALIAS: ${{ secrets.CI_KEY_ALIAS }}
          CI_KEY_PASSWORD: ${{ secrets.CI_KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

          # Localizar el APK generado
          RUTA_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "Unsigned APK path: $RUTA_APK"

          # Firma del APK con apksigner
          "$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS }}/apksigner" \
            sign \
            --ks fichero.jks \
            --ks-pass "pass:${CI_KEYSTORE_PASSWORD}" \
            --ks-key-alias "${CI_KEY_ALIAS}" \
            --key-pass "pass:${CI_KEY_PASSWORD}" \
            --out app-signed.apk \
            "$RUTA_APK"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: release-apk
          path: calculadoraVelocidadMedia/app-signed.apk
          retention-days: 5

  # 7. Despliegue del APK firmado en GitHub Releases (solo para tags que comiencen con "calculadoraVelocidadMedia-")
  deploy:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [assemble-release]
    # Filtro corregido con sintaxis nativa de GitHub Actions
    if: startsWith(github.ref, 'refs/tags/') && startsWith(github.ref_name, 'calculadoraVelocidadMedia-') 
    # Declaración explícita de permisos mínimos requeridos
    permissions:
      contents: write
    steps:
      # Configura checkout
      - uses: actions/checkout@v4

      # Descarga el apk firmado desde el job anterior
      - name: Download signed APK 
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: ./release-files

      # Actualiza el nombre de la versión en el archivo de cambios (cambios.md) con la versión extraída del tag
      - name: Extract version from tag
        id: version
        run: |
          TAG="${{ github.ref_name }}"  # ej. "calculadoraVelocidadMedia-v1.0"
          VERSION_NAME=$(echo "$TAG" | sed 's/^calculadoraVelocidadMedia-//')
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT

      # Genera el changelog de la release y copia el APK firmado con un nombre que incluya la versión
      - name: Generate release changelog
        run: |
          if [ -f "./release-files/app-signed.apk" ]; then
            cp ./release-files/app-signed.apk "calculadoraVelocidadMedia-${{ steps.version.outputs.version }}.apk"
          fi

      #  Realiza la publicación de la release en GitHub con el APK firmado y el changelog
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: calculadoraVelocidadMedia v${{ steps.version.outputs.version }}
          body_path: cambios.md
          files: |
            calculadoraVelocidadMedia-${{ steps.version.outputs.version }}.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}